server:
  port: 10240
mqtt:
  url: tcp://broker.emqx.io:1883
  topic:
    subscribe: /v1/zrapp/service/data,/v1/zrapp/service/event
spring:
  datasource:
    url: jdbc:sqlite:D:/dev/cpp/gateway/zriot.db
    driver-class-name: org.sqlite.JDBC
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  jackson:
    default-property-inclusion: always
    time-zone: GMT+8
logging:
  level:
    root: info
    com:
      alibaba:
        nacos: error
  file:
    name: /logs/embedded.log
mybatis-plus:
  mapper-locations: mapper/*.xml,mapper/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl